#!/bin/bash

title="Fwulf << "
widthpercent=13

typeset -A menu
menu=(
    ["    App Launcher"]="rofi -terminal alacritty -show drun"
    ["类  Current Window"]="rofi -terminal alacritty -show windowcd"
    ["缾  Windows"]="rofi -terminal alacritty -show window"
    ["    File Browser"]="rofi -terminal alacritty -show filebrowser"
    ["⏻    Powermenu"]="~/.config/rofi/powermenu/powermenu.sh"
    ["    Combi"]="rofi -show combi"
)

typeset -A colors
colors=(
    [-color-window]="#0000ff, #ffffff, #ffffff"
    [-color-normal]="#ffffff, #000000, #eee8d5, #000473, #ffffff"
    [-color-active]="#fdf6e3, #268bd2, #eee8d5, #268bd2, #fdf6e3"
    [-color-urgent]="#fdf6e3, #dc322f, #eee8d5, #dc322f, #fdf6e3"
)
